### ISSUE TITLE
Fails immediately: missing resources

### ISSUE THREAD

**Issue by ghost** [DanWahlin/Angular2-Forms#1]
Ran tsc, then the app (there are no tests) and it's missing config.js.  

"Fixed" that by touching an empty config.js but that leads to: 

 "Cannot GET /src/app/bootstrap"

**Comment by DanWahlin** [comment]
Thanks - my bad on config.js not being included. I updated the .gitignore awhile back and didn't realize it was excluding that file. Just tried it all from scratch and seems to be working properly now.

**Comment by ghost** [comment]
Confirmed working, thanks.
